# DATA PREPROCESSING

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv('/home/piyush/Desktop/Code/100-DAYS-OF-ML-CODE/Datasets/Day3.csv')

## This dataset is a basketball dataset which contains desription about players in the   following way

* Height
* Weight
* percentage of succesfull Field_goals
* percentage of succesfull Free_throws
* average points scored per game


In [3]:
dataset

Height   Weight  Field_goals  Free_throws  Points_pergame       State
0   6.8225    0.442        0.672        9.200            11.6     Newyork
1   6.3000  180.000        0.435        0.797            11.7  California
2   6.4000  190.000        0.456        0.761            15.8     Florida
3   6.2000  180.000        0.416        0.651             8.6     Newyork
4   6.9000  205.000        0.449        0.900            23.2  California
5   6.4000  225.000        0.431        0.780            27.4     Florida
6   6.3000  185.000        0.487        0.771             9.3     Newyork
7   6.8000  235.000        0.469        0.750            16.0  California
8   6.9000  235.000        0.435        0.818             4.7     Florida
9   6.7000  210.000        0.480        0.825            12.5     Newyork
10  6.9000  245.000        0.516        0.632            20.1  California
11  6.9000  245.000        0.493        0.757             9.1     Florida
12  6.3000  185.000        0.374        0.709             8.1     Newyork
13  6.1000  185.000        0.424        0.782             8.6  California
14  6.2000  180.000        0.441        0.775            20.3     Florida
15  6.8000  220.000        0.503        0.880            25.0     Newyork
16  6.5000  194.000        0.503        0.833            19.2  California
17  7.6000  225.000        0.425        0.571             3.3     Florida
18  6.3000  210.000        0.371        0.816            11.2     Newyork
19  7.1000  240.000        0.504        0.714            10.5  California
20  6.8000  225.000        0.400        0.765            10.1     Florida
21  7.3000  263.000        0.482        0.655             7.2     Newyork
22  6.4000  210.000        0.475        0.244            13.6  California
23  6.8000  235.000        0.428        0.728             9.0     Florida
24  7.2000  230.000        0.559        0.721            24.6     Newyork
25  6.4000  190.000        0.441        0.757            12.6  California
26  6.6000  220.000        0.492        0.747             5.6     Florida
27  6.8000  210.000        0.402        0.739             8.7     Newyork
28  6.1000  180.000        0.415        0.713             7.7  California
29  6.5000  235.000        0.492        0.742            24.1     Florida

In [4]:
X = dataset.iloc[:, : -2].values
Y = dataset.iloc[:, 4].values

In [5]:
X

array([[6.8225e+00, 4.4200e-01, 6.7200e-01, 9.2000e+00],
       [6.3000e+00, 1.8000e+02, 4.3500e-01, 7.9700e-01],
       [6.4000e+00, 1.9000e+02, 4.5600e-01, 7.6100e-01],
       [6.2000e+00, 1.8000e+02, 4.1600e-01, 6.5100e-01],
       [6.9000e+00, 2.0500e+02, 4.4900e-01, 9.0000e-01],
       [6.4000e+00, 2.2500e+02, 4.3100e-01, 7.8000e-01],
       [6.3000e+00, 1.8500e+02, 4.8700e-01, 7.7100e-01],
       [6.8000e+00, 2.3500e+02, 4.6900e-01, 7.5000e-01],
       [6.9000e+00, 2.3500e+02, 4.3500e-01, 8.1800e-01],
       [6.7000e+00, 2.1000e+02, 4.8000e-01, 8.2500e-01],
       [6.9000e+00, 2.4500e+02, 5.1600e-01, 6.3200e-01],
       [6.9000e+00, 2.4500e+02, 4.9300e-01, 7.5700e-01],
       [6.3000e+00, 1.8500e+02, 3.7400e-01, 7.0900e-01],
       [6.1000e+00, 1.8500e+02, 4.2400e-01, 7.8200e-01],
       [6.2000e+00, 1.8000e+02, 4.4100e-01, 7.7500e-01],
       [6.8000e+00, 2.2000e+02, 5.0300e-01, 8.8000e-01],
       [6.5000e+00, 1.9400e+02, 5.0300e-01, 8.3300e-01],
       [7.6000e+00, 2.2500e+02,

In [6]:
Y

array([11.6, 11.7, 15.8,  8.6, 23.2, 27.4,  9.3, 16. ,  4.7, 12.5, 20.1,
        9.1,  8.1,  8.6, 20.3, 25. , 19.2,  3.3, 11.2, 10.5, 10.1,  7.2,
       13.6,  9. , 24.6, 12.6,  5.6,  8.7,  7.7, 24.1])

## Note: Since we have not included ant categorical data that's why there is no need of anytype of encoding

## Avoiding Dummy Variable Trap

In [7]:
X = X[:, 2:]
X

array([[0.672, 9.2  ],
       [0.435, 0.797],
       [0.456, 0.761],
       [0.416, 0.651],
       [0.449, 0.9  ],
       [0.431, 0.78 ],
       [0.487, 0.771],
       [0.469, 0.75 ],
       [0.435, 0.818],
       [0.48 , 0.825],
       [0.516, 0.632],
       [0.493, 0.757],
       [0.374, 0.709],
       [0.424, 0.782],
       [0.441, 0.775],
       [0.503, 0.88 ],
       [0.503, 0.833],
       [0.425, 0.571],
       [0.371, 0.816],
       [0.504, 0.714],
       [0.4  , 0.765],
       [0.482, 0.655],
       [0.475, 0.244],
       [0.428, 0.728],
       [0.559, 0.721],
       [0.441, 0.757],
       [0.492, 0.747],
       [0.402, 0.739],
       [0.415, 0.713],
       [0.492, 0.742]])

## Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size =0.2, random_state=0)

## Fitting Multiple Linear Regression to the Training set

In [9]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()
le.fit(X_train, Y_train)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [10]:
prediction = le.predict(X_test)

print(prediction)


[13.54391349 11.54970073 11.90416239 16.74613485 15.37492082 18.78254977]
